# Site settings
title: "Early Days of Ethereum"
description: "Preserving the history and stories of the people who built Ethereum."
baseurl: ""
url: "https://www.earlydaysofeth.org"
author: "Bob Summerwill"

# Additional SEO settings
lang: en_US
timezone: America/Vancouver
keywords: "Ethereum, blockchain, cryptocurrency, Vitalik Buterin, Gavin Wood, early history, foundation, development"

# Site verification (add your verification codes when available)
google_site_verification: "VAAK0u6FRzaYZ9K8SHqFh_4HOGGGh7-dqDjc"
bing_site_verification: ""

# Analytics (add your tracking IDs when available)
google_analytics: "G-K07HLJER91"

# Social sharing image - using optimized version
image: /images/archive.org/ethereum.org/20140428062102/thumbnails/internetarchive_ethereum.org_20140428062102_thumbnail_og_general.png

# Social media settings
twitter:
  username: bobsummerwill
  card: summary_large_image

# Open Graph settings
social:
  name: "Early Days of Ethereum"
  links:
    - https://github.com/bobsummerwill/EarlyDaysOfEthereum
    - https://x.com/bobsummerwill
    - https://linkedin.com/in/bobsummerwill

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

# Collections
collections:
  articles:
    output: true
    permalink: /articles/:name/
  people:
    output: true
    permalink: /people/:name/
  videos:
    output: true
    permalink: /videos/:path/
  posts:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
    values:
      image: /images/archive.org/ethereum.org/20140428062102/thumbnails/internetarchive_ethereum.org_20140428062102_thumbnail_og_general.png
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "post"
      image: /images/archive.org/ethereum.org/20140428062102/thumbnails/internetarchive_ethereum.org_20140428062102_thumbnail_og_general.png
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      image: /images/archive.org/ethereum.org/20140428062102/thumbnails/internetarchive_ethereum.org_20140428062102_thumbnail_og_general.png
  - scope:
      path: ""
      type: "people"
    values:
      layout: "person"
      image: /images/archive.org/ethereum.org/20140428062102/thumbnails/internetarchive_ethereum.org_20140428062102_thumbnail_og_general.png
  - scope:
      path: ""
      type: "videos"
    values:
      layout: "video"
      image: /images/archive.org/ethereum.org/20140428062102/thumbnails/internetarchive_ethereum.org_20140428062102_thumbnail_og_general.png

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
